baseURL = 'https://script-fu.github.io/artbox/'
languageCode = 'en-GB'
title = 'Artbox'
theme = 'hextra'

[params]
description = "Art, Painting, Illustration"

[params.theme]
default = "dark"  # light | dark | system
displayToggle = false

[params.navbar]
displayTitle = true
displayLogo = false

[params.navbar.logo]
path = "images/logo.svg"
dark = "images/logo-dark.svg"
link = "/artbox/"
width = 40
height = 20

[page]
width = "normal"

[footer]
enable = false
displayCopyright = false
displayPoweredBy = false
width = "normal"

[metadata]
displayUpdatedDate = true
dateFormat = "January 2, 2006"

[search]
enable = true
type = "flexsearch"

[search.flexsearch]
index = "content"
tokenize = "forward"

[blog.list]
displayTags = true
sortBy = "date"
sortOrder = "desc"
# date | lastmod | publishDate | title | weight

[highlight.copy]
enable = true
display = "hover"

[params.comments]
enable = false
type = "giscus"

[params.comments.giscus]
repo = "<repository>"
repoId = "<repository ID>"
category = "<category>"
categoryId = "<category ID>"

[menu]

[[menu.main]]
name = "About"
pageRef = "hub/about/"
weight = 1

[[menu.main]]
name = "Installation"
pageRef = "hub/docs/folder/Installation"
weight = 1
[[menu.main]]

name = "Documentation"
pageRef = "hub/docs/folder/"
weight = 1

[[menu.main]]
name = "Features"
pageRef = "hub/feature-test/folder/"
weight = 1

[[menu.main]]
name = "Guides"
pageRef = "hub/guides/folder/"
weight = 3

[[menu.main]]
name = "Search"
weight = 4

  [menu.main.params]
  type = "search"

[params.search]
enable = true
type = "flexsearch"

[params.search.flexsearch]
index = "content"  # index page by: content | summary | heading | title

[services.googleAnalytics]
ID = "G-MEASUREMENT_ID"

