baseURL = 'https://script-fu.github.io/artbox/'
languageCode = 'en-GB'
title = 'Artbox'
theme = 'hextra'

[params]
description = "Artbox is a free, open-source digital painting and illustration app for Linux. Lightweight, themeable, and easy to build from source."
keywords = "Artbox, digital painting, illustration software, Linux art app, GIMP alternative, open-source art app, Debian, AppImage, themeable UI"

[params.theme]
default = "dark"  # light | dark | system
displayToggle = false

[params.navbar]
displayTitle = true
displayLogo = true

[params.navbar.logo]
path = "images/favicon/android-chrome-192x192.png"
link = "/artbox/"
width = 40
height = 40

[page]
width = "normal"

[params.footer]
enable = false
displayCopyright = false
displayPoweredBy = false
width = "normal"

[metadata]
displayUpdatedDate = true
dateFormat = "January 2, 2006"

[search]
enable = true
type = "flexsearch"

[search.flexsearch]
index = "content"
tokenize = "forward"

[blog.list]
displayTags = true
sortBy = "date"
sortOrder = "desc"
# date | lastmod | publishDate | title | weight

[highlight.copy]
enable = true
display = "hover"

[params.comments]
enable = false
type = "giscus"

[params.comments.giscus]
repo = "<repository>"
repoId = "<repository ID>"
category = "<category>"
categoryId = "<category ID>"

[menu]

[[menu.main]]
name = "sweeneyworks"
url = "https://sweeneyworks.com/"
weight = 1

[[menu.main]]
name = "AppImage"
pageRef = "hub/docs/folder/AppImage"
weight = 2

[[menu.main]]
name = "About"
pageRef = "hub/about/"
weight = 8

[[menu.main]]
name = "Installation"
pageRef = "hub/docs/folder/Installation"
weight = 3

[[menu.main]]
name = "Themes"
pageRef = "hub/themes/folder/"
weight = 3

[[menu.main]]
name = "Funky-Fu"
url = "https://script-fu.github.io/funky/"
weight = 8

[[menu.main]]
name = "Documentation"
pageRef = "hub/docs/folder/"
weight = 4

[[menu.main]]
name = "Features"
pageRef = "hub/feature-test/folder/"
weight = 7

[[menu.main]]
name = "Guides"
pageRef = "hub/guides/folder/"
weight = 5

[[menu.main]]
name = "Search"
weight = 9

  [menu.main.params]
  type = "search"

[params.search]
enable = true
type = "flexsearch"

[params.search.flexsearch]
index = "content"  # index page by: content | summary | heading | title

[services.googleAnalytics]
ID = "G-MEASUREMENT_ID"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true